/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import pais.ViewPais;
import estado.ViewEstado;

/**
 *
 * @author gleyd_000
 */
public class ViewPrincipal extends javax.swing.JFrame {

    public static boolean iniPais = false;
    public static boolean iniEstado = false;
    
    /**
     * Creates new form Principal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenuAmbiente = new javax.swing.JMenu();
        jMenuTabelas = new javax.swing.JMenu();
        jMenuLocalidade = new javax.swing.JMenu();
        jMenuItemPais = new javax.swing.JMenuItem();
        jMenuItemEstado = new javax.swing.JMenuItem();
        jMenuJanela = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGFSystem");
        setExtendedState(6);

        jMenuAmbiente.setMnemonic('A');
        jMenuAmbiente.setText("Ambiente");

        jMenuTabelas.setMnemonic('T');
        jMenuTabelas.setText("Tabelas");

        jMenuLocalidade.setMnemonic('L');
        jMenuLocalidade.setText("Localidade");

        jMenuItemPais.setMnemonic('P');
        jMenuItemPais.setText("Pais");
        jMenuItemPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaisActionPerformed(evt);
            }
        });
        jMenuLocalidade.add(jMenuItemPais);

        jMenuItemEstado.setMnemonic('E');
        jMenuItemEstado.setText("Estado");
        jMenuItemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoActionPerformed(evt);
            }
        });
        jMenuLocalidade.add(jMenuItemEstado);

        jMenuTabelas.add(jMenuLocalidade);

        jMenuAmbiente.add(jMenuTabelas);

        menuBar.add(jMenuAmbiente);

        jMenuJanela.setText("Janela");
        menuBar.add(jMenuJanela);

        jMenuAjuda.setMnemonic('h');
        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setMnemonic('a');
        jMenuItemSobre.setText("Sobre");
        jMenuAjuda.add(jMenuItemSobre);

        menuBar.add(jMenuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaisActionPerformed
        // TODO add your handling code here:
        if (!iniPais) {
            ViewPais pais = new ViewPais();
            desktopPane.add(pais);
            pais.setVisible(true);
            pais.setPosicao();
        }
    }//GEN-LAST:event_jMenuItemPaisActionPerformed

    private void jMenuItemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoActionPerformed
        // TODO add your handling code here:
        if (!iniEstado) {
            ViewEstado estado = new ViewEstado();
            desktopPane.add(estado);
            estado.setVisible(true);
            estado.setPosicao();
        }
    }//GEN-LAST:event_jMenuItemEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuAmbiente;
    private javax.swing.JMenuItem jMenuItemEstado;
    private javax.swing.JMenuItem jMenuItemPais;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuJanela;
    private javax.swing.JMenu jMenuLocalidade;
    private javax.swing.JMenu jMenuTabelas;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
