/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pais;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import util.ControlaView;

/**
 *
 * @author Gleydson Israel
 */
public class ViewPais extends javax.swing.JInternalFrame {

    ModelPais modelPais = new ModelPais();
    ControllerPais controllerPais = new ControllerPais();
    ArrayList<ModelPais> listaModelPais = new ArrayList<>();

    int registro = 0;

    SimpleDateFormat formatDateTime = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    private enum StatePais {
        INSERINDO,
        EDITANDO,
        CONSULTANDO,
        DELETANDO,
        VAZIO
    }
    private StatePais statePais = StatePais.CONSULTANDO;

    /**
     * Creates new form ViewPais
     */
    public ViewPais() {
        initComponents();
        habilitaComponente(statePais);
        carregaDados(0);
        jTablePais.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonInsert = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonCancel = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButtonRefresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePais = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelIdentificacao = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabelDataInclusao = new javax.swing.JLabel();
        jLabelDataInclusao1 = new javax.swing.JLabel();
        jTextDataInclusao = new javax.swing.JTextField();
        jTextDataAlteracao = new javax.swing.JTextField();
        jPanelDadosFiscais = new javax.swing.JPanel();
        jLabelCodigoBacen = new javax.swing.JLabel();
        jTextCodigoBacen = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemInsert = new javax.swing.JMenuItem();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCancel = new javax.swing.JMenuItem();
        jMenuItemAccept = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRefresh = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClose = new javax.swing.JMenuItem();

        setTitle("Pais");
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName("Pais"); // NOI18N
        setPreferredSize(new java.awt.Dimension(752, 400));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonInsert.setToolTipText("Novo Registro");
        jButtonInsert.setFocusable(false);
        jButtonInsert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonInsert.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonInsert.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonInsert.setSelected(true);
        jButtonInsert.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_add.png"))); // NOI18N
        jButtonInsert.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert(evt);
            }
        });
        jToolBar1.add(jButtonInsert);

        jButtonEdit.setToolTipText("Editar Registro");
        jButtonEdit.setFocusable(false);
        jButtonEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdit.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonEdit.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonEdit.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonEdit.setSelected(true);
        jButtonEdit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_edit.png"))); // NOI18N
        jButtonEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit(evt);
            }
        });
        jToolBar1.add(jButtonEdit);

        jButtonDelete.setToolTipText("Excluir Registro");
        jButtonDelete.setFocusable(false);
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonDelete.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonDelete.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonDelete.setSelected(true);
        jButtonDelete.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_delete.png"))); // NOI18N
        jButtonDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });
        jToolBar1.add(jButtonDelete);
        jToolBar1.add(jSeparator2);

        jButtonCancel.setToolTipText("Cancelar");
        jButtonCancel.setFocusable(false);
        jButtonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancel.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonCancel.setSelected(true);
        jButtonCancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButtonCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel(evt);
            }
        });
        jToolBar1.add(jButtonCancel);

        jButtonAccept.setToolTipText("Confirmar");
        jButtonAccept.setFocusable(false);
        jButtonAccept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAccept.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonAccept.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonAccept.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonAccept.setSelected(true);
        jButtonAccept.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jButtonAccept.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept(evt);
            }
        });
        jToolBar1.add(jButtonAccept);
        jToolBar1.add(jSeparator3);

        jButtonRefresh.setToolTipText("Atualizar Registros");
        jButtonRefresh.setFocusable(false);
        jButtonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRefresh.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonRefresh.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonRefresh.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonRefresh.setSelected(true);
        jButtonRefresh.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_refresh.png"))); // NOI18N
        jButtonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh(evt);
            }
        });
        jToolBar1.add(jButtonRefresh);
        jToolBar1.add(jSeparator1);

        jButtonClose.setToolTipText("Fechar");
        jButtonClose.setFocusable(false);
        jButtonClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClose.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonClose.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonClose.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonClose.setSelected(true);
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jButtonClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });
        jToolBar1.add(jButtonClose);

        jTablePais.setAutoCreateRowSorter(true);
        jTablePais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Código BACEN", "Data de Inclusão", "Data de Alteração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePais);
        if (jTablePais.getColumnModel().getColumnCount() > 0) {
            jTablePais.getColumnModel().getColumn(1).setPreferredWidth(800);
            jTablePais.getColumnModel().getColumn(2).setPreferredWidth(125);
            jTablePais.getColumnModel().getColumn(3).setMinWidth(0);
            jTablePais.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTablePais.getColumnModel().getColumn(3).setMaxWidth(0);
            jTablePais.getColumnModel().getColumn(4).setMinWidth(0);
            jTablePais.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTablePais.getColumnModel().getColumn(4).setMaxWidth(0);
        }
        jTablePais.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                atualizaInformacao();
            }
        });

        jLabelCodigo.setText("Código");
        jLabelCodigo.setEnabled(false);

        jTextCodigo.setEnabled(false);

        jLabelNome.setText("Nome");

        util.MyDocument docNome = new util.MyDocument(60);
        jTextNome.setDocument(docNome);
        jTextNome.setEditable(false);

        jLabelDataInclusao.setText("Data de Inclusão");
        jLabelDataInclusao.setEnabled(false);

        jLabelDataInclusao1.setText("Data Alteração");
        jLabelDataInclusao1.setEnabled(false);

        jTextDataInclusao.setEditable(false);
        jTextDataInclusao.setEnabled(false);

        jTextDataAlteracao.setEditable(false);
        jTextDataAlteracao.setEnabled(false);

        javax.swing.GroupLayout jPanelIdentificacaoLayout = new javax.swing.GroupLayout(jPanelIdentificacao);
        jPanelIdentificacao.setLayout(jPanelIdentificacaoLayout);
        jPanelIdentificacaoLayout.setHorizontalGroup(
            jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNome, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                        .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDataInclusao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDataInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDataInclusao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelIdentificacaoLayout.setVerticalGroup(
            jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDataInclusao1)
                        .addComponent(jTextDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodigo)
                        .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataInclusao)
                        .addComponent(jTextDataInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Identificação", jPanelIdentificacao);

        jLabelCodigoBacen.setText("Código BACEN");

        util.MyDocument docCodigoBacen = new util.MyDocument(4);
        jTextCodigoBacen.setDocument(docCodigoBacen);
        jTextCodigoBacen.setEditable(false);

        javax.swing.GroupLayout jPanelDadosFiscaisLayout = new javax.swing.GroupLayout(jPanelDadosFiscais);
        jPanelDadosFiscais.setLayout(jPanelDadosFiscaisLayout);
        jPanelDadosFiscaisLayout.setHorizontalGroup(
            jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFiscaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCodigoBacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCodigoBacen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(598, Short.MAX_VALUE))
        );
        jPanelDadosFiscaisLayout.setVerticalGroup(
            jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFiscaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoBacen)
                    .addComponent(jTextCodigoBacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informações Adicionais", jPanelDadosFiscais);

        jMenuRegistro.setText("Registro");
        jMenuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert(evt);
            }
        });

        jMenuItemInsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_add.png"))); // NOI18N
        jMenuItemInsert.setText("Novo");
        jMenuItemInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert(evt);
            }
        });
        jMenuRegistro.add(jMenuItemInsert);

        jMenuItemEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_edit.png"))); // NOI18N
        jMenuItemEdit.setText("Editar");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit(evt);
            }
        });
        jMenuRegistro.add(jMenuItemEdit);

        jMenuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_delete.png"))); // NOI18N
        jMenuItemDelete.setText("Excluir");
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });
        jMenuRegistro.add(jMenuItemDelete);
        jMenuRegistro.add(jSeparator4);

        jMenuItemCancel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jMenuItemCancel.setText("Cancelar");
        jMenuItemCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel(evt);
            }
        });
        jMenuRegistro.add(jMenuItemCancel);

        jMenuItemAccept.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jMenuItemAccept.setText("Confirmar");
        jMenuItemAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept(evt);
            }
        });
        jMenuRegistro.add(jMenuItemAccept);
        jMenuRegistro.add(jSeparator5);

        jMenuItemRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_refresh.png"))); // NOI18N
        jMenuItemRefresh.setText("Atualizar");
        jMenuItemRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh(evt);
            }
        });
        jMenuRegistro.add(jMenuItemRefresh);
        jMenuRegistro.add(jSeparator6);

        jMenuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jMenuItemClose.setText("Fechar");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });
        jMenuRegistro.add(jMenuItemClose);

        jMenuBar1.add(jMenuRegistro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        getAccessibleContext().setAccessibleDescription("Cadastro de Pais");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert
        // TODO add your handling code here:
        statePais = StatePais.INSERINDO;
        limpaInformacao();
        habilitaComponente(statePais);
        jTabbedPane1.setSelectedIndex(0);
        jTextNome.requestFocus();
    }//GEN-LAST:event_insert

    private void edit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit
        // TODO add your handling code here:
        statePais = StatePais.EDITANDO;
        habilitaComponente(statePais);
        jTabbedPane1.setSelectedIndex(0);
        jTextNome.requestFocus();
    }//GEN-LAST:event_edit

    private void delete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Confirma exclusão do registro?", "", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            statePais = StatePais.DELETANDO;
            if (jTextCodigo.getText() != "") {
                modelPais.setIdPais(Integer.parseInt(jTextCodigo.getText()));
            }
            modelPais.setNome(jTextNome.getText());
            int focusRegistro = jTablePais.getSelectedRow() - 1;
            if (controllerPais.deletePais(modelPais)) {
                carregaDados(focusRegistro);
                statePais = StatePais.CONSULTANDO;
                if (jTablePais.getRowCount() > 0) {
                    habilitaComponente(statePais);
                } else {
                    habilitaComponente(StatePais.VAZIO);
                }
                JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_delete

    private void cancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Cancela operação?", "", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
            return;
        }
        limpaInformacao();
        statePais = StatePais.CONSULTANDO;
        habilitaComponente(statePais);
        carregaDados(jTablePais.getSelectedRow() + 1);
    }//GEN-LAST:event_cancel

    private void accept(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept
        // TODO add your handling code here:
        int ultimoRegistro = 0;
        boolean ok = false;
        if (statePais == StatePais.EDITANDO) {
            ultimoRegistro = Integer.parseInt(jTextCodigo.getText());
            modelPais.setIdPais(Integer.parseInt(jTextCodigo.getText()));
        }
        modelPais.setNome(jTextNome.getText());
        modelPais.setCodBacen(jTextCodigoBacen.getText());

        switch (statePais) {
            case INSERINDO:
                if (controllerPais.insertPais(modelPais)) {
                    ultimoRegistro = controllerPais.ultimoRegistro(modelPais);
                    ok = true;
                }
                break;
            case EDITANDO:
                if (controllerPais.editPais(modelPais)) {
                    ok = true;
                }
                break;
        }
        if (ok) {
            carregaDados(ultimoRegistro);
            statePais = StatePais.CONSULTANDO;
            habilitaComponente(statePais);
            JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!");
        }
    }//GEN-LAST:event_accept

    private void refresh(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh
        // TODO add your handling code here:
        carregaDados(0);
    }//GEN-LAST:event_refresh

    private void close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close
        // TODO add your handling code here:
        if (statePais != StatePais.CONSULTANDO) {
            if (JOptionPane.showConfirmDialog(this, "Deseja cancelar a operação?", "", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }
        }
        this.dispose();
    }//GEN-LAST:event_close

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        ControlaView.viewPais = null;
    }//GEN-LAST:event_formInternalFrameClosed

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void carregaDados(int pFocusRegistro) {
        listaModelPais = controllerPais.getListaPais();
        DefaultTableModel tablePais = (DefaultTableModel) jTablePais.getModel();
        tablePais.setNumRows(0);
        jTablePais.updateUI();
        int cont = listaModelPais.size();
        if (cont > 0) {
            for (int i = 0; i < cont; i++) {
                tablePais.addRow(new Object[]{
                    listaModelPais.get(i).getIdPais(),
                    listaModelPais.get(i).getNome(),
                    listaModelPais.get(i).getCodBacen(),
                    formatDateTime.format(listaModelPais.get(i).getDataInclusao()),
                    formatDateTime.format(listaModelPais.get(i).getDataAlteracao())
                });
            }
            int focusRegistro = 0;
            if (pFocusRegistro > 0) {
                switch (statePais) {
                    case DELETANDO:
                        focusRegistro = pFocusRegistro;
                        break;
                    default:
                        int index = jTablePais.getColumnModel().getColumnIndex("Código");
                        for (int linha = 0; linha < jTablePais.getRowCount(); linha++) {
                            int valor = (int) jTablePais.getValueAt(linha, index);
                            if (pFocusRegistro == valor) {
                                focusRegistro = linha;
                                break;
                            }
                        }
                        break;
                }
            }
            jTablePais.setRowSelectionInterval(focusRegistro, focusRegistro);
        } else {
            habilitaComponente(ViewPais.StatePais.VAZIO);
        }

    }

    private void habilitaComponente(ViewPais.StatePais pStatePais) {
        switch (pStatePais) {
            case INSERINDO:
                jTablePais.setEnabled(false);

                jButtonInsert.setEnabled(false);
                jButtonEdit.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonCancel.setEnabled(true);
                jButtonAccept.setEnabled(true);
                jButtonRefresh.setEnabled(false);

                jMenuItemInsert.setEnabled(false);
                jMenuItemEdit.setEnabled(false);
                jMenuItemDelete.setEnabled(false);
                jMenuItemCancel.setEnabled(true);
                jMenuItemAccept.setEnabled(true);
                jMenuItemRefresh.setEnabled(false);

                jTextNome.setEditable(true);
                jTextCodigoBacen.setEditable(true);

                break;
            case EDITANDO:
                jTablePais.setEnabled(false);

                jButtonInsert.setEnabled(false);
                jButtonEdit.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonCancel.setEnabled(true);
                jButtonAccept.setEnabled(true);
                jButtonRefresh.setEnabled(false);

                jMenuItemInsert.setEnabled(false);
                jMenuItemEdit.setEnabled(false);
                jMenuItemDelete.setEnabled(false);
                jMenuItemCancel.setEnabled(true);
                jMenuItemAccept.setEnabled(true);
                jMenuItemRefresh.setEnabled(false);

                jTextNome.setEditable(true);
                jTextCodigoBacen.setEditable(true);

                break;
            case CONSULTANDO:
                jTablePais.setEnabled(true);

                jButtonInsert.setEnabled(true);
                jButtonEdit.setEnabled(true);
                jButtonDelete.setEnabled(true);
                jButtonCancel.setEnabled(false);
                jButtonAccept.setEnabled(false);
                jButtonRefresh.setEnabled(true);

                jMenuItemInsert.setEnabled(true);
                jMenuItemEdit.setEnabled(true);
                jMenuItemDelete.setEnabled(true);
                jMenuItemCancel.setEnabled(false);
                jMenuItemAccept.setEnabled(false);
                jMenuItemRefresh.setEnabled(true);

                jTextNome.setEditable(false);
                jTextCodigoBacen.setEditable(false);

                break;
            case VAZIO:
                jTablePais.setEnabled(false);

                jButtonInsert.setEnabled(true);
                jButtonEdit.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonCancel.setEnabled(false);
                jButtonAccept.setEnabled(false);
                jButtonRefresh.setEnabled(true);

                jMenuItemInsert.setEnabled(true);
                jMenuItemEdit.setEnabled(false);
                jMenuItemDelete.setEnabled(false);
                jMenuItemCancel.setEnabled(false);
                jMenuItemAccept.setEnabled(false);
                jMenuItemRefresh.setEnabled(true);

                jTextNome.setEditable(false);
                jTextCodigoBacen.setEditable(false);

                break;
        }
    }

    private void atualizaInformacao() {
        registro = jTablePais.getSelectedRow();
        if (registro < 0) {
            limpaInformacao();
        } else {
            int index;

            index = jTablePais.getColumnModel().getColumnIndex("Código");
            int idPais = (int) jTablePais.getValueAt(registro, index);
            jTextCodigo.setText(Integer.toString(idPais));

            index = jTablePais.getColumnModel().getColumnIndex("Nome");
            jTextNome.setText((String) jTablePais.getValueAt(registro, index));

            index = jTablePais.getColumnModel().getColumnIndex("Código BACEN");
            jTextCodigoBacen.setText((String) jTablePais.getValueAt(registro, index));

            index = jTablePais.getColumnModel().getColumnIndex("Data de Inclusão");
            jTextDataInclusao.setText((String) jTablePais.getValueAt(registro, index));

            index = jTablePais.getColumnModel().getColumnIndex("Data de Alteração");
            jTextDataAlteracao.setText((String) jTablePais.getValueAt(registro, index));
        }
    }

    private void limpaInformacao() {
        jTextCodigo.setText(null);
        jTextNome.setText(null);
        jTextCodigoBacen.setText(null);
        jTextDataInclusao.setText(null);
        jTextDataAlteracao.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigoBacen;
    private javax.swing.JLabel jLabelDataInclusao;
    private javax.swing.JLabel jLabelDataInclusao1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAccept;
    private javax.swing.JMenuItem jMenuItemCancel;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemInsert;
    private javax.swing.JMenuItem jMenuItemRefresh;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JPanel jPanelDadosFiscais;
    private javax.swing.JPanel jPanelIdentificacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePais;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCodigoBacen;
    private javax.swing.JTextField jTextDataAlteracao;
    private javax.swing.JTextField jTextDataInclusao;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
