/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyEvent;
import pais.*;

/**
 *
 * @author Gleydson Israel
 */
public final class Procurar extends javax.swing.JDialog {

    private final String tabelaConsulta;
    private boolean ok = false;
    private int chave;
    private String descricao;

    public int getChave() {
        return chave;
    }

    public boolean getOk() {
        return ok;
    }

    public String getDescricao() {
        return descricao;
    }

    /**
     * Creates new form Procurar
     *
     * @param parent
     * @param modal
     * @param pTabelaConsulta
     */
    public Procurar(java.awt.Frame parent, boolean modal, String pTabelaConsulta) {
        super(parent, modal);
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icone.png")).getImage());
        initComponents();
        this.tabelaConsulta = pTabelaConsulta;
        carregaInformacoes();
        jTableListaDados.requestFocus();
        jTableListaDados.setRowSelectionInterval(0, 0);
    }

    public void carregaInformacoes() {
        switch (tabelaConsulta) {
            case "pais":
                this.setTitle("Pesquisa Pais");
                ControllerPais controllerPais = new ControllerPais();
                ArrayList<ModelPais> listaModelPais = new ArrayList<>();
                listaModelPais = controllerPais.getListaPais();
                DefaultTableModel tablePais = (DefaultTableModel) jTableListaDados.getModel();
                jComboBoxCampo.removeAllItems();
                jComboBoxCampo.addItem("Código");
                jComboBoxCampo.addItem("Nome");
                jComboBoxCampo.addItem("Código BACEN");
                tablePais.addColumn("Código");
                tablePais.addColumn("Nome");
                tablePais.addColumn("Código BACEN");
                tablePais.setNumRows(0);
                jTableListaDados.updateUI();
                int cont = listaModelPais.size();
                if (cont > 0) {
                    for (int i = 0; i < cont; i++) {
                        tablePais.addRow(new Object[]{
                            listaModelPais.get(i).getIdPais(),
                            listaModelPais.get(i).getNome(),
                            listaModelPais.get(i).getCodBacen(),});
                    }
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaDados = new javax.swing.JTable();
        jLabelFiltrar = new javax.swing.JLabel();
        jTextFieldFiltrar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabelCampo = new javax.swing.JLabel();
        jComboBoxCampo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("jDialogProcurar"); // NOI18N

        jTableListaDados.setAutoCreateRowSorter(true);
        jTableListaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane2.setViewportView(jTableListaDados);

    jLabelFiltrar.setText("Filtrar");

    jTextFieldFiltrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldFiltrarActionPerformed(evt);
        }
    });

    jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
    jButtonCancelar.setText("Cancelar");
    jButtonCancelar.setMaximumSize(new java.awt.Dimension(95, 30));
    jButtonCancelar.setMinimumSize(new java.awt.Dimension(95, 30));
    jButtonCancelar.setPreferredSize(new java.awt.Dimension(115, 30));
    jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCancelarActionPerformed(evt);
        }
    });

    jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
    jButtonConfirmar.setText("Confirmar");
    jButtonConfirmar.setMaximumSize(new java.awt.Dimension(95, 30));
    jButtonConfirmar.setMinimumSize(new java.awt.Dimension(99, 30));
    jButtonConfirmar.setPreferredSize(new java.awt.Dimension(115, 30));
    jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonConfirmarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    jLabelCampo.setText("Campo");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelFiltrar)
                        .addComponent(jLabelCampo))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldFiltrar)
                        .addComponent(jComboBoxCampo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelCampo)
                .addComponent(jComboBoxCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelFiltrar))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel listaDados = (DefaultTableModel) this.jTableListaDados.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(listaDados);
        jTableListaDados.setRowSorter(sorter);
        String text = jTextFieldFiltrar.getText();
        int indexCol = jComboBoxCampo.getSelectedIndex();
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, indexCol));
        jTableListaDados.requestFocus();
        jTableListaDados.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_jTextFieldFiltrarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        int indexRow = jTableListaDados.getSelectedRow();
        if (indexRow >= 0) {
            int indexColumn;
            switch (tabelaConsulta) {
                default:
                    indexColumn = jTableListaDados.getColumnModel().getColumnIndex("Código");
                    this.chave = (int) jTableListaDados.getValueAt(indexRow, indexColumn);

                    indexColumn = jTableListaDados.getColumnModel().getColumnIndex("Nome");
                    this.descricao = (String) jTableListaDados.getValueAt(indexRow, indexColumn);
            }
            this.ok = true;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Operação bloqueada. Favor selecionar um registro.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Procurar dialog = new Procurar(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxCampo;
    private javax.swing.JLabel jLabelCampo;
    private javax.swing.JLabel jLabelFiltrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListaDados;
    private javax.swing.JTextField jTextFieldFiltrar;
    // End of variables declaration//GEN-END:variables
}
