/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estado;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import principal.ViewPrincipal;
import model.ModelEstadoPais;
import dao.DaoEstadoPais;
import controller.ControllerEstadoPais;
import pais.ViewPais;

/**
 *
 * @author Gleydso Israel
 */
public class ViewEstado extends javax.swing.JInternalFrame {

    ModelEstado modelEstado = new ModelEstado();
    ControllerEstado controllerEstado = new ControllerEstado();
    ModelEstadoPais modelEstadoPais = new ModelEstadoPais();
    ControllerEstadoPais controllerEstadoPais = new ControllerEstadoPais();
    ArrayList<ModelEstadoPais> listaModelEstadoPais = new ArrayList<>();

    int registro = 0;

    SimpleDateFormat formatDateTime = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    private enum StateEstado {
        INSERINDO,
        EDITANDO,
        CONSULTANDO,
        DELETANDO,
        VAZIO
    }
    private StateEstado stateEstado = StateEstado.CONSULTANDO;

    /**
     * Creates new form ViewEstado
     */
    public ViewEstado() {
        initComponents();
        habilitaComponente(stateEstado);
        carregaDados(0);
        jTableEstado.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonInsert = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonCancel = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButtonRefresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelIdentificacao = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jLabelPais = new javax.swing.JLabel();
        jTextNomePais = new javax.swing.JTextField();
        jLabelDataInclusao = new javax.swing.JLabel();
        jLabelDataInclusao1 = new javax.swing.JLabel();
        jTextDataInclusao = new javax.swing.JTextField();
        jTextDataAlteracao = new javax.swing.JTextField();
        jLabelNome1 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextCodigoPais = new javax.swing.JTextField();
        jButtonLocalizar = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jPanelDadosFiscais = new javax.swing.JPanel();
        jLabelCodigoIbge = new javax.swing.JLabel();
        jTextCodigoIbge = new javax.swing.JTextField();
        jLabelSigla = new javax.swing.JLabel();
        jTextSigla = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemInsert = new javax.swing.JMenuItem();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCancel = new javax.swing.JMenuItem();
        jMenuItemAccept = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRefresh = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClose = new javax.swing.JMenuItem();

        setTitle("Estado");
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(741, 430));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonInsert.setToolTipText("Novo Registro");
        jButtonInsert.setFocusable(false);
        jButtonInsert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonInsert.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonInsert.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonInsert.setSelected(true);
        jButtonInsert.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_add.png"))); // NOI18N
        jButtonInsert.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert(evt);
            }
        });
        jToolBar1.add(jButtonInsert);

        jButtonEdit.setToolTipText("Editar Registro");
        jButtonEdit.setFocusable(false);
        jButtonEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdit.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonEdit.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonEdit.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonEdit.setSelected(true);
        jButtonEdit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_edit.png"))); // NOI18N
        jButtonEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit(evt);
            }
        });
        jToolBar1.add(jButtonEdit);

        jButtonDelete.setToolTipText("Excluir Registro");
        jButtonDelete.setFocusable(false);
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonDelete.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonDelete.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonDelete.setSelected(true);
        jButtonDelete.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_delete.png"))); // NOI18N
        jButtonDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });
        jToolBar1.add(jButtonDelete);
        jToolBar1.add(jSeparator2);

        jButtonCancel.setToolTipText("Cancelar");
        jButtonCancel.setFocusable(false);
        jButtonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancel.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonCancel.setSelected(true);
        jButtonCancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButtonCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel(evt);
            }
        });
        jToolBar1.add(jButtonCancel);

        jButtonAccept.setToolTipText("Confirmar");
        jButtonAccept.setFocusable(false);
        jButtonAccept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAccept.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonAccept.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonAccept.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonAccept.setSelected(true);
        jButtonAccept.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jButtonAccept.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept(evt);
            }
        });
        jToolBar1.add(jButtonAccept);
        jToolBar1.add(jSeparator3);

        jButtonRefresh.setToolTipText("Atualizar Registros");
        jButtonRefresh.setFocusable(false);
        jButtonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRefresh.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonRefresh.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonRefresh.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonRefresh.setSelected(true);
        jButtonRefresh.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_refresh.png"))); // NOI18N
        jButtonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh(evt);
            }
        });
        jToolBar1.add(jButtonRefresh);
        jToolBar1.add(jSeparator1);

        jButtonClose.setToolTipText("Fechar");
        jButtonClose.setFocusable(false);
        jButtonClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClose.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonClose.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonClose.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonClose.setSelected(true);
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jButtonClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });
        jToolBar1.add(jButtonClose);

        jTableEstado.setAutoCreateRowSorter(true);
        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Pais", "Nome", "Sigla", "Código IBGE", "Data de Inclusão", "Data de Alteração", "Código Pais"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEstado);
        if (jTableEstado.getColumnModel().getColumnCount() > 0) {
            jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(600);
            jTableEstado.getColumnModel().getColumn(4).setMinWidth(0);
            jTableEstado.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTableEstado.getColumnModel().getColumn(4).setMaxWidth(0);
            jTableEstado.getColumnModel().getColumn(5).setMinWidth(0);
            jTableEstado.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTableEstado.getColumnModel().getColumn(5).setMaxWidth(0);
            jTableEstado.getColumnModel().getColumn(6).setMinWidth(0);
            jTableEstado.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTableEstado.getColumnModel().getColumn(6).setMaxWidth(0);
            jTableEstado.getColumnModel().getColumn(7).setMinWidth(0);
            jTableEstado.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTableEstado.getColumnModel().getColumn(7).setMaxWidth(0);
        }
        jTableEstado.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                atualizaInformacao();
            }
        });

        jLabelCodigo.setText("Código");
        jLabelCodigo.setEnabled(false);

        jTextCodigo.setEnabled(false);

        jLabelPais.setText("Pais*");

        jTextNomePais.setEditable(false);
        jTextNomePais.setEnabled(false);

        jLabelDataInclusao.setText("Data de Inclusão");
        jLabelDataInclusao.setEnabled(false);

        jLabelDataInclusao1.setText("Data Alteração");
        jLabelDataInclusao1.setEnabled(false);

        jTextDataInclusao.setEditable(false);
        jTextDataInclusao.setEnabled(false);

        jTextDataAlteracao.setEditable(false);
        jTextDataAlteracao.setEnabled(false);

        jLabelNome1.setText("Nome*");

        util.MyDocument docNome = new util.MyDocument(60);
        jTextNome.setDocument(docNome);
        jTextNome.setEditable(false);

        jTextCodigoPais.setEnabled(false);

        jButtonLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/find.png"))); // NOI18N
        jButtonLocalizar.setMaximumSize(new java.awt.Dimension(49, 30));
        jButtonLocalizar.setMinimumSize(new java.awt.Dimension(49, 30));
        jButtonLocalizar.setPreferredSize(new java.awt.Dimension(49, 30));

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButtonAdicionar.setMaximumSize(new java.awt.Dimension(49, 30));
        jButtonAdicionar.setMinimumSize(new java.awt.Dimension(49, 30));
        jButtonAdicionar.setPreferredSize(new java.awt.Dimension(49, 30));

        javax.swing.GroupLayout jPanelIdentificacaoLayout = new javax.swing.GroupLayout(jPanelIdentificacao);
        jPanelIdentificacao.setLayout(jPanelIdentificacaoLayout);
        jPanelIdentificacaoLayout.setHorizontalGroup(
            jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                        .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPais)
                            .addComponent(jLabelCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCodigoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                                .addComponent(jTextNomePais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                                .addComponent(jLabelDataInclusao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDataInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDataInclusao1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                        .addComponent(jLabelNome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNome, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIdentificacaoLayout.setVerticalGroup(
            jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDataInclusao1)
                        .addComponent(jTextDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodigo)
                        .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataInclusao)
                        .addComponent(jTextDataInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIdentificacaoLayout.createSequentialGroup()
                        .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPais)
                                .addComponent(jTextNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCodigoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome1)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("Identificação", jPanelIdentificacao);

        jLabelCodigoIbge.setText("Código IBGE");

        util.MyDocument docCodigoBacen = new util.MyDocument(4);
        jTextCodigoIbge.setDocument(docCodigoBacen);
        jTextCodigoIbge.setEditable(false);

        jLabelSigla.setText("Sigla*");

        util.MyDocument docSigla = new util.MyDocument(2);
        jTextSigla.setDocument(docSigla);
        jTextSigla.setEditable(false);

        javax.swing.GroupLayout jPanelDadosFiscaisLayout = new javax.swing.GroupLayout(jPanelDadosFiscais);
        jPanelDadosFiscais.setLayout(jPanelDadosFiscaisLayout);
        jPanelDadosFiscaisLayout.setHorizontalGroup(
            jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFiscaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigoIbge)
                    .addComponent(jLabelSigla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodigoIbge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanelDadosFiscaisLayout.setVerticalGroup(
            jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosFiscaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoIbge)
                    .addComponent(jTextCodigoIbge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSigla)
                    .addComponent(jTextSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informações Adicionais", jPanelDadosFiscais);

        jMenuRegistro.setText("Registro");
        jMenuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert(evt);
            }
        });

        jMenuItemInsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_add.png"))); // NOI18N
        jMenuItemInsert.setText("Novo");
        jMenuItemInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert(evt);
            }
        });
        jMenuRegistro.add(jMenuItemInsert);

        jMenuItemEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_edit.png"))); // NOI18N
        jMenuItemEdit.setText("Editar");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit(evt);
            }
        });
        jMenuRegistro.add(jMenuItemEdit);

        jMenuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_delete.png"))); // NOI18N
        jMenuItemDelete.setText("Excluir");
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });
        jMenuRegistro.add(jMenuItemDelete);
        jMenuRegistro.add(jSeparator4);

        jMenuItemCancel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jMenuItemCancel.setText("Cancelar");
        jMenuItemCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel(evt);
            }
        });
        jMenuRegistro.add(jMenuItemCancel);

        jMenuItemAccept.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jMenuItemAccept.setText("Confirmar");
        jMenuItemAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept(evt);
            }
        });
        jMenuRegistro.add(jMenuItemAccept);
        jMenuRegistro.add(jSeparator5);

        jMenuItemRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_refresh.png"))); // NOI18N
        jMenuItemRefresh.setText("Atualizar");
        jMenuItemRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh(evt);
            }
        });
        jMenuRegistro.add(jMenuItemRefresh);
        jMenuRegistro.add(jSeparator6);

        jMenuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jMenuItemClose.setText("Fechar");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });
        jMenuRegistro.add(jMenuItemClose);

        jMenuBar1.add(jMenuRegistro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Cadastro de Estado");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert
        // TODO add your handling code here:
        stateEstado = StateEstado.INSERINDO;
        limpaInformacao();
        habilitaComponente(stateEstado);
        jTabbedPane1.setSelectedIndex(0);
        jTextCodigoPais.requestFocus();
    }//GEN-LAST:event_insert

    private void edit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit
        // TODO add your handling code here:
        stateEstado = StateEstado.EDITANDO;
        habilitaComponente(stateEstado);
        jTabbedPane1.setSelectedIndex(0);
        jTextNome.requestFocus();
    }//GEN-LAST:event_edit

    private void delete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Confirma exclusão do registro?", "", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            stateEstado = StateEstado.DELETANDO;
            if (jTextCodigo.getText() != "") {
                modelEstado.setIdEstado(Integer.parseInt(jTextCodigo.getText()));
            }
            modelEstado.setNome(jTextNome.getText());
            int focusRegistro = jTableEstado.getSelectedRow() - 1;
            if (controllerEstado.deleteEstado(modelEstado)) {
                carregaDados(focusRegistro);
                stateEstado = StateEstado.CONSULTANDO;
                if (jTableEstado.getRowCount() > 0) {
                    habilitaComponente(stateEstado);
                } else {
                    habilitaComponente(StateEstado.VAZIO);
                }
                JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_delete

    private void cancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Cancela operação?", "", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
            return;
        }
        limpaInformacao();
        stateEstado = StateEstado.CONSULTANDO;
        habilitaComponente(stateEstado);
        carregaDados(jTableEstado.getSelectedRow() + 1);
    }//GEN-LAST:event_cancel

    private void accept(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept
        // TODO add your handling code here:
        if (!validaInformacoes()) {
            return;
        }
        int ultimoRegistro = 0;
        boolean ok = false;
        if (stateEstado == StateEstado.EDITANDO) {
            ultimoRegistro = Integer.parseInt(jTextCodigo.getText());
            modelEstado.setIdEstado(Integer.parseInt(jTextCodigo.getText()));
        }
        modelEstado.setIdPais(Integer.parseInt(jTextCodigoPais.getText()));
        modelEstado.setSigla(jTextSigla.getText());
        modelEstado.setNome(jTextNome.getText());
        if (!jTextCodigoIbge.getText().trim().equals("")) {
            modelEstado.setCodIbge(Integer.parseInt(jTextCodigoIbge.getText()));
        }

        switch (stateEstado) {
            case INSERINDO:
                if (controllerEstado.insertEstado(modelEstado)) {
                    ultimoRegistro = controllerEstado.ultimoRegistro(modelEstado);
                    ok = true;
                }
                break;
            case EDITANDO:
                if (controllerEstado.editEstado(modelEstado)) {
                    ok = true;
                }
                break;
        }
        if (ok) {
            carregaDados(ultimoRegistro);
            stateEstado = StateEstado.CONSULTANDO;
            habilitaComponente(stateEstado);
            JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!");
        }
    }//GEN-LAST:event_accept

    private void refresh(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh
        // TODO add your handling code here:
        carregaDados(0);
    }//GEN-LAST:event_refresh

    private void close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close
        // TODO add your handling code here:
        if (stateEstado != StateEstado.CONSULTANDO) {
            if (JOptionPane.showConfirmDialog(this, "Deseja cancelar a operação?", "", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }
        }
        this.dispose();
    }//GEN-LAST:event_close

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        ViewPrincipal.iniEstado = true;
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        ViewPrincipal.iniEstado = false;
    }//GEN-LAST:event_formInternalFrameClosed

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void carregaDados(int pFocusRegistro) {
        listaModelEstadoPais = controllerEstadoPais.getListaEstadoPais();
        DefaultTableModel tableEstado = (DefaultTableModel) jTableEstado.getModel();
        tableEstado.setNumRows(0);
        jTableEstado.updateUI();
        int cont = listaModelEstadoPais.size();
        if (cont > 0) {
            for (int i = 0; i < cont; i++) {
                tableEstado.addRow(new Object[]{
                    listaModelEstadoPais.get(i).getModelEstado().getIdEstado(),
                    listaModelEstadoPais.get(i).getModelPais().getNome(),
                    listaModelEstadoPais.get(i).getModelEstado().getNome(),
                    listaModelEstadoPais.get(i).getModelEstado().getSigla(),
                    listaModelEstadoPais.get(i).getModelEstado().getCodIbge(),
                    formatDateTime.format(listaModelEstadoPais.get(i).getModelEstado().getDataInclusao()),
                    formatDateTime.format(listaModelEstadoPais.get(i).getModelEstado().getDataAlteracao()),
                    listaModelEstadoPais.get(i).getModelEstado().getIdPais(),});
            }
            int focusRegistro = 0;
            if (pFocusRegistro > 0) {
                switch (stateEstado) {
                    case DELETANDO:
                        focusRegistro = pFocusRegistro;
                        break;
                    default:
                        int index = jTableEstado.getColumnModel().getColumnIndex("Código");
                        for (int linha = 0; linha < jTableEstado.getRowCount(); linha++) {
                            int valor = (int) jTableEstado.getValueAt(linha, index);
                            if (pFocusRegistro == valor) {
                                focusRegistro = linha;
                                break;
                            }
                        }
                        break;
                }
            }
            jTableEstado.setRowSelectionInterval(focusRegistro, focusRegistro);
        } else {
            habilitaComponente(ViewEstado.StateEstado.VAZIO);
        }

    }

    private void habilitaComponente(ViewEstado.StateEstado pStateEstado) {
        switch (pStateEstado) {
            case INSERINDO:
                jTableEstado.setEnabled(false);

                jButtonInsert.setEnabled(false);
                jButtonEdit.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonCancel.setEnabled(true);
                jButtonAccept.setEnabled(true);
                jButtonRefresh.setEnabled(false);
                jButtonLocalizar.setEnabled(true);
                jButtonAdicionar.setEnabled(true);

                jMenuItemInsert.setEnabled(false);
                jMenuItemEdit.setEnabled(false);
                jMenuItemDelete.setEnabled(false);
                jMenuItemCancel.setEnabled(true);
                jMenuItemAccept.setEnabled(true);
                jMenuItemRefresh.setEnabled(false);

                jTextCodigoPais.setEditable(true);
                jTextCodigoPais.setEnabled(true);
                jTextNome.setEditable(true);
                jTextCodigoIbge.setEditable(true);
                jTextSigla.setEditable(true);

                jLabelPais.setEnabled(true);

                break;
            case EDITANDO:
                jTableEstado.setEnabled(false);

                jButtonInsert.setEnabled(false);
                jButtonEdit.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonCancel.setEnabled(true);
                jButtonAccept.setEnabled(true);
                jButtonRefresh.setEnabled(false);
                jButtonLocalizar.setEnabled(false);
                jButtonAdicionar.setEnabled(false);

                jMenuItemInsert.setEnabled(false);
                jMenuItemEdit.setEnabled(false);
                jMenuItemDelete.setEnabled(false);
                jMenuItemCancel.setEnabled(true);
                jMenuItemAccept.setEnabled(true);
                jMenuItemRefresh.setEnabled(false);

                jTextCodigoPais.setEditable(false);
                jTextCodigoPais.setEnabled(false);
                jTextNome.setEditable(true);
                jTextCodigoIbge.setEditable(true);
                jTextSigla.setEditable(true);

                jLabelPais.setEnabled(false);

                break;
            case CONSULTANDO:
                jTableEstado.setEnabled(true);

                jButtonInsert.setEnabled(true);
                jButtonEdit.setEnabled(true);
                jButtonDelete.setEnabled(true);
                jButtonCancel.setEnabled(false);
                jButtonAccept.setEnabled(false);
                jButtonRefresh.setEnabled(true);
                jButtonLocalizar.setEnabled(false);
                jButtonAdicionar.setEnabled(false);

                jMenuItemInsert.setEnabled(true);
                jMenuItemEdit.setEnabled(true);
                jMenuItemDelete.setEnabled(true);
                jMenuItemCancel.setEnabled(false);
                jMenuItemAccept.setEnabled(false);
                jMenuItemRefresh.setEnabled(true);

                jTextCodigoPais.setEditable(false);
                jTextCodigoPais.setEnabled(false);
                jTextNome.setEditable(false);
                jTextCodigoIbge.setEditable(false);
                jTextSigla.setEditable(false);

                jLabelPais.setEnabled(false);

                break;
            case VAZIO:
                jTableEstado.setEnabled(false);

                jButtonInsert.setEnabled(true);
                jButtonEdit.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonCancel.setEnabled(false);
                jButtonAccept.setEnabled(false);
                jButtonRefresh.setEnabled(true);
                jButtonLocalizar.setEnabled(false);
                jButtonAdicionar.setEnabled(false);

                jMenuItemInsert.setEnabled(true);
                jMenuItemEdit.setEnabled(false);
                jMenuItemDelete.setEnabled(false);
                jMenuItemCancel.setEnabled(false);
                jMenuItemAccept.setEnabled(false);
                jMenuItemRefresh.setEnabled(true);

                jTextCodigoPais.setEditable(false);
                jTextCodigoPais.setEnabled(false);
                jTextNome.setEditable(false);
                jTextCodigoIbge.setEditable(false);
                jTextSigla.setEditable(false);

                jLabelPais.setEnabled(false);

                break;
        }
    }

    private void atualizaInformacao() {
        registro = jTableEstado.getSelectedRow();
        if (registro < 0) {
            limpaInformacao();
        } else {
            int index;

            index = jTableEstado.getColumnModel().getColumnIndex("Código");
            int idEstado = (int) jTableEstado.getValueAt(registro, index);
            jTextCodigo.setText(Integer.toString(idEstado));

            index = jTableEstado.getColumnModel().getColumnIndex("Data de Inclusão");
            jTextDataInclusao.setText((String) jTableEstado.getValueAt(registro, index));

            index = jTableEstado.getColumnModel().getColumnIndex("Data de Alteração");
            jTextDataAlteracao.setText((String) jTableEstado.getValueAt(registro, index));

            index = jTableEstado.getColumnModel().getColumnIndex("Código Pais");
            int idPais = (int) jTableEstado.getValueAt(registro, index);
            jTextCodigoPais.setText(Integer.toString(idPais));

            index = jTableEstado.getColumnModel().getColumnIndex("Pais");
            jTextNomePais.setText((String) jTableEstado.getValueAt(registro, index));

            index = jTableEstado.getColumnModel().getColumnIndex("Nome");
            jTextNome.setText((String) jTableEstado.getValueAt(registro, index));

            index = jTableEstado.getColumnModel().getColumnIndex("Código IBGE");
            Integer codigoIbge = (Integer) jTableEstado.getValueAt(registro, index);
            jTextCodigoIbge.setText(Integer.toString(codigoIbge));

            index = jTableEstado.getColumnModel().getColumnIndex("Sigla");
            jTextSigla.setText((String) jTableEstado.getValueAt(registro, index));
        }
    }

    private void limpaInformacao() {
        jTextCodigo.setText(null);
        jTextDataInclusao.setText(null);
        jTextDataAlteracao.setText(null);
        jTextCodigoPais.setText(null);
        jTextNomePais.setText(null);
        jTextNome.setText(null);
        jTextCodigoIbge.setText(null);
        jTextSigla.setText(null);
    }

    private boolean validaInformacoes() {
        try {
            boolean abort = false;

            boolean requestFocus = false;

            String mensagem = "Operação bloqueada. Os seguintes dados devem ser informados: \n";

            if (jTextCodigoPais.getText().trim().equals("")) {
                mensagem = mensagem + "Pais. \n";
                if (!requestFocus) {
                    jTabbedPane1.setSelectedIndex(0);
                    jTextCodigoPais.requestFocus();
                    requestFocus = true;
                }
                abort = true;
            }

            if (jTextNome.getText().trim().equals("")) {
                mensagem = mensagem + "Nome. \n";
                if (!requestFocus) {
                    jTabbedPane1.setSelectedIndex(0);
                    jTextNome.requestFocus();
                    requestFocus = true;
                }
                abort = true;
            }

            if (jTextSigla.getText().trim().equals("")) {
                mensagem = mensagem + "Sigla. \n";
                if (!requestFocus) {
                    jTabbedPane1.setSelectedIndex(1);
                    jTextSigla.requestFocus();
                    requestFocus = true;
                }
                abort = true;
            }

            if (abort) {
                throw new Exception(mensagem);
            }

            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigoIbge;
    private javax.swing.JLabel jLabelDataInclusao;
    private javax.swing.JLabel jLabelDataInclusao1;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelSigla;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAccept;
    private javax.swing.JMenuItem jMenuItemCancel;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemInsert;
    private javax.swing.JMenuItem jMenuItemRefresh;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JPanel jPanelDadosFiscais;
    private javax.swing.JPanel jPanelIdentificacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCodigoIbge;
    private javax.swing.JTextField jTextCodigoPais;
    private javax.swing.JTextField jTextDataAlteracao;
    private javax.swing.JTextField jTextDataInclusao;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNomePais;
    private javax.swing.JTextField jTextSigla;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
